version: "3.8"

services:
  cuda:
    image: nvidia/cuda:10.2-devel-ubuntu18.04
    volumes:
      - .:/opt/bitcrack
    working_dir: /opt/bitcrack
    command: make BUILD_CUDA=1

  opencl:
    image: rocm/rocm-terminal
    #devices:
    #  - "/dev/kfd"
    volumes:
      - .:/opt/bitcrack
    working_dir: /opt/bitcrack
    command: make BUILD_OPENCL=1
